export const INCREMENT_COUNT = 'INCREMENT_COUNT';

// audio files
export const DECODE_FILE_SUCCESS = 'DECODE_FILE_SUCCESS';
export const DECODE_FILE_FAIL = 'DECODE_FILE_FAIL';

// db
export const DB_LOAD_INITIAL_RESULTS = 'DB_LOAD_INITIAL_RESULTS';
export const DB_LOAD_INITIAL_RESULTS_FAIL = 'DB_LOAD_INITIAL_RESULTS_FAIL';
export const DB_LOAD_INITIAL_RESULTS_START = 'DB_LOAD_INITIAL_RESULTS_START';
export const DB_LOAD_INITIAL_RESULTS_SUCCESS = 'DB_LOAD_INITIAL_RESULTS_SUCCESS';

// results list
export const LIST_SELECT_FILE = 'LIST_SELECT_FILE';

// play controls
export const PLAYBACK_TOGGLE_AUTO_PLAY = 'PLAYBACK_TOGGLE_AUTO_PLAY';
export const PLAYBACK_TOGGLE_PLAY = 'PLAYBACK_TOGGLE_PLAY';
