// app
export const INIT_APP = 'INIT_APP';

// audio files
export const SELECT_FILE = 'SELECT_FILE';
export const BUFFER_FETCHED_FROM_CACHE_SUCCESS = 'BUFFER_FETCHED_FROM_CACHE_SUCCESS';
export const RESULTS_SET_SORT_TYPE = 'RESULTS_SET_SORT_TYPE';
export const RESULTS_SET_SORT_DIRECTION = 'RESULTS_SET_SORT_DIRECTION';

// db
export const DB_LOAD_INITIAL_RESULTS = 'DB_LOAD_INITIAL_RESULTS';
export const DB_LOAD_INITIAL_RESULTS_FAIL = 'DB_LOAD_INITIAL_RESULTS_FAIL';
export const DB_LOAD_INITIAL_RESULTS_START = 'DB_LOAD_INITIAL_RESULTS_START';
export const DB_LOAD_INITIAL_RESULTS_SUCCESS = 'DB_LOAD_INITIAL_RESULTS_SUCCESS';

// results list
export const LIST_SELECT_FILE_ID = 'LIST_SELECT_FILE_ID';

// play controls
export const PLAYBACK_TOGGLE_AUTO_PLAY = 'PLAYBACK_TOGGLE_AUTO_PLAY';
export const PLAYBACK_TOGGLE_CYCLE_PLAY = 'PLAYBACK_TOGGLE_CYCLE_PLAY';
export const PLAYBACK_TOGGLE_PLAY = 'PLAYBACK_TOGGLE_PLAY';
export const PLAYBACK_SET_PLAYING = 'PLAYBACK_SET_PLAYING';
export const PLAYBACK_SET_STOPPED = 'PLAYBACK_SET_STOPPED';

// imports
export const IMPORT_BUFFER_READ = 'IMPORT_BUFFER_READ';
export const IMPORT_BUFFER_READ_ERROR = 'IMPORT_BUFFER_READ_ERROR';
export const IMPORT_CREATE_NEW = 'IMPORT_CREATE_NEW';
export const IMPORT_METADATA_DECODED = 'IMPORT_METADATA_DECODED';
export const IMPORT_ONE_PATH = 'IMPORT_ONE_PATH';
export const IMPORT_READ_STATS = 'IMPORT_READ_STATS';
export const IMPORT_READY_TO_INSERT = 'IMPORT_READY_TO_INSERT';
export const IMPORT_REMOVE_IMPORT = 'IMPORT_REMOVE_IMPORT';

// library
export const SET_LIBRARY_ID = 'SET_LIBRARY_ID';
