export const INCREMENT_COUNT = 'INCREMENT_COUNT';

// audio files
export const LOAD_FILES = 'LOAD_FILES';
export const LOAD_FILES_START = 'LOAD_FILES_START';
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS';
export const LOAD_FILES_FAIL = 'LOAD_FILES_FAIL';
export const SELECT_FILE = 'SELECT_FILE';
export const DECODE_FILE_SUCCESS = 'DECODE_FILE_SUCCESS';
export const DECODE_FILE_FAIL = 'DECODE_FILE_FAIL';

// db
export const DB_LOAD_INITIAL_RESULTS = 'DB_LOAD_INITIAL_RESULTS';
export const DB_LOAD_INITIAL_RESULTS_FAIL = 'DB_LOAD_INITIAL_RESULTS_FAIL';
export const DB_LOAD_INITIAL_RESULTS_START = 'DB_LOAD_INITIAL_RESULTS_START';
export const DB_LOAD_INITIAL_RESULTS_SUCCESS = 'DB_LOAD_INITIAL_RESULTS_SUCCESS';
